version: '3.4'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx_auth_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./uploads:/usr/share/nginx/html
    ports:
      - 8080:80
  
  api:
    image: node:14-alpine
    container_name: nginx_auth_api
    working_dir: /home/node
    volumes:
      - ./api:/home/node
    command: sh -c 'npm install && node ./index.js'